### ISSUE TITLE
Cannot bower install ngDatepicker

### ISSUE THREAD

**Issue by vanbrigoli** [sonatype/bower-nexus3-resolver#11]
I tried installing ngDatepicker with bower but i got an error:

**ENORESTARGET** No version found that was able to satisfy *

Additional error details:
No versions found in nexus+http://localhost:8081/repository/bower-all/ngDatepicker

Btw, I am using Nexus OSS 3.1.0-04 and have configured bower(proxy) with remote storage pointing to https://bower.herokuapp.com

With .bowerrc:
{
 "registry" : {
        "search" : [
            "http://localhost:8081/repository/bower-all/"
        ]
   },
    "nexus": {
        "username": "admin",
        "password": "admin123"
    },
    "resolvers": [ "bower-nexus3-resolver" ]
}

Thanks.

**Comment by joedragons** [comment]
@vanbrigoli I believe you're running into https://issues.sonatype.org/browse/NEXUS-10291.  You'll note https://github.com/jkuri/ngDatepicker has no tags and our resolver does not currently deal well with that/*.  I am going to close this since it's covered there but feel free to follow/vote there.
