### ISSUE TITLE
Does not work with feature branches as version - fetches from github

### ISSUE THREAD

**Issue by mawie81** [sonatype/bower-nexus3-resolver#14]
We are using git-flow and therefore have feature branches of our bower dependencies.
While a version like
```"my-module": "develop"``` or a tag ```"my-module": "1.1.0"``` works without issues something like this ```"my-module": "feature/my-feature"``` will try to fetch the package from github: https://github.com/feature/my-feature.git

Is there any way around this?

**Comment by fjmilens3** [comment]
Not at this time, unfortunately. Bower recognizes that as (GitHub) "shorthand" and the custom Nexus 3 resolver doesn't come into play at that point. 

We have had some internal discussions about additional changes on the Nexus 3 side that could perhaps play nicely with the Bower `shorthand-resolver` configuration option, but it's not something we have on our immediate roadmap.

We are interested in how many people would be interested in such a feature as it might help us in scheduling further investigation on supporting that. If you'd be interested, open a JIRA ticket for us (the "Dev - Nexus" team) at https://issues.sonatype.org/ and follow that for news.

Thanks for getting in touch!
