### ISSUE TITLE
Integration with Jenkins?

### ISSUE THREAD

**Issue by stegmai** [sonatype/bower-nexus3-resolver#16]
Hi all!

I have included the bower-nexus3-resolver in our environment. From local development everything works out as expected. Unfortunately, i get the following issue after integration into Jenkins:

```
+ bower prune
+ export bower_registry__search=http://nexus3.intranet.onelogic.de:18081/repository/bower-all
+ export bower_resolvers=bower-nexus3-resolver
+ bower install
bower angular#1.6.3   MODULE_NOT_FOUND Cannot find module 'bower-nexus3-resolver'
```

The configurations are the same locally and remote on Jenkins. Any ideas?

**Comment by fjmilens3** [comment]
This message in particular

    bower angular#1.6.3   MODULE_NOT_FOUND Cannot find module 'bower-nexus3-resolver'

Makes me wonder if the bower-nexus3-resolver has been installed globally on that system and is accessible for when Jenkins is running `bower` commands?

**Comment by stegmai** [comment]
The setup is as following: The Jenkins and its workers is configured by docker images. The project using the resolver has a dedicated worker and within the CLI of the run configuration of the jobs, the npm packges are being installed. It is also visible in the tree, that the dependency has been resolved and installed. 

```
| `-- source-map-support@0.4.14 
+-- bower-nexus3-resolver@1.0.1 
| +-- q@1.4.1 
| +-- request@2.67.0 
| | +-- aws-sign2@0.6.0 
```

I don´t know how i should install it in a different way since the commands are the same as if i log into the bash on the worker and execute the npm commands there. Any clues?

**Comment by stegmai** [comment]
ah, allright...this one did it:

```
npm install -g bower-nexus3-resolver
```
