### ISSUE TITLE
Private GitHub repo credentials

### ISSUE THREAD

**Issue by andrew-boutin** [sonatype/bower-nexus3-resolver#17]
Hello, I'm having issues installing my Bower package.

I have Nexus 3 set up to host my Bower repo. I've registered my private GitHub repo as a package in Nexus. I have anonymous read access enabled for Nexus. I'm running this in a Jenkins job where I have environment variables `GITHUB_USERNAME` & `GITHUB_PASSWORD`. Here's my configuration:

```
{
    "directory": "public/js/djtk/",
    "registry": {
        "search": [
            "https://url/repository/bower-repo-name",
            "https://bower.herokuapp.com"
        ]
    },
    "nexus": {
        "username": "${GITHUB_USERNAME}",
        "password": "${GITHUB_PASSWORD}"
    },
    "resolvers": ["bower-nexus3-resolver"]
}
```

I keep getting:
```Additional error details:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/org/repo.git/'
```

Is there something wrong with this configuration?

**Comment by andrew-boutin** [comment]
Some further investigation. I ran this in a Docker container with a fresh environment hard coding my GITHUB username and password in the nexus section of the .bowerrc. I was still prompted for my GitHub username and password. What's the point of setting it in the .bowerrc if it's going to be ignored?

**Comment by joedragons** [comment]
@andrew-boutin What are you trying to do when you get that message?  With anon read on you shouldn't need any auth unless you're pushing to hosted or you changed your anonymous access or something.

**Comment by andrew-boutin** [comment]
@joedragons Nexus has anonymous read access, but the GitHub repo is private and requires credentials for read access.

Also, I'm running `bower install`.

**Comment by joedragons** [comment]
@andrew-boutin I suspect the username and password as you have it configured are just being sent to NXRM.  If so, it's hitting that auth and requesting the github credentials.  Have you tried entering the GitHub credentials into the proxy configuration via the HTTP section of the proxy in the UI?

**Comment by andrew-boutin** [comment]
@joedragons I have not, I'll have to check that out. Thanks for the tip! I'll let you know how it goes, hopefully can get around to this later this week.

**Comment by andrew-boutin** [comment]
@joedragons I check the settings page for my Bower repository and is `Hosted` not `Proxy` so I don't believe I can configure what you were talking about.

**Comment by DarthHater** [comment]
@andrew-boutin can you file an issue at: https://issues.sonatype.org/browse/NEXUS

Those get reviewed a fair bit quicker.

**Comment by andrew-boutin** [comment]
I created a Support request since I'm not sure that there is a bug or issue yet. https://support.sonatype.com/hc/en-us/requests/18823?flash_digest=236b8574b8a2ec11a75b8572b069485eeaf4b437

**Comment by andrew-boutin** [comment]
> The credentials in the "nexus" section are used for authenticating against the Nexus server, not github.
> 
> A hosted bower registry doesn't actually host the components, it hosts the metadata. The components are hosted in the original location (usually a git repository).
> 
> I'm actually not sure what the best way to get bower to send credentials for the github is. But discussion here:
> 
> https://github.com/bower/bower/issues/1456
> 
> Indicates that using a pluggable resolver for github enterprise is the way to go:
> 
> https://bower.io/docs/pluggable-resolvers/
> 
> I haven't tried that myself though.
> 
> Rich

**Comment by andrew-boutin** [comment]
I will have to look into pluggable resolvers.
