### ISSUE TITLE
Temporary files are not purged

### ISSUE THREAD

**Issue by Turgon37** [sonatype/bower-nexus3-resolver#29]
We are running bower behind a nexus registry

I notice that temporary files are not purged once the assets are downloaded

To reproduce with bower version 1.0.4

1) use a bowerrc like this

```
user@helper02 ~/web/tmp/test $ cat .bowerrc 
{
  "registry" : {
    "search" : [ "https://registry.example.com/repository/bower-proxy/" ]
  },
  "resolvers" : [ "bower-nexus3-resolver" ]
}
```

2) run bower install

```
bower install --force
```

3) notice that temporary files are not removed

```
user@helper02 ~/web/tmp/test # ls -l /tmp/tmp-*
-rw-r--r-- 1 helper helper  295882 juil. 23 14:40 /tmp/tmp-251786HLa5n7RL5K
-rw-r--r-- 1 helper helper 2414926 juil. 23 14:40 /tmp/tmp-25179YcOMMoIXwcY
-rw-r--r-- 1 helper helper 4176288 juil. 23 14:40 /tmp/tmp-2517JQK1uwzbw5Hv
-rw-r--r-- 1 helper helper 2366973 juil. 23 14:40 /tmp/tmp-2517KuIMgaEteczj
-rw-r--r-- 1 helper helper  189823 juil. 23 14:40 /tmp/tmp-2517OE4dfVxsy8De
-rw-r--r-- 1 helper helper  428166 juil. 23 14:40 /tmp/tmp-2517R2zA2GwZ72V1
-rw-r--r-- 1 helper helper  428166 juil. 23 14:40 /tmp/tmp-2517SvBwONOTaAW9
```

I've found an issue that can be related with tmp module https://github.com/bower/bower/issues/345

How can we debug this ?

**Comment by joedragons** [comment]
Does that not happen when you don't use NXRM?

**Comment by Turgon37** [comment]
no, without nxrm, the temporary folder path is /tmp/[linux username]/bower the the folder is empty  at the end of the download process

**Comment by Turgon37** [comment]
Hello, do you have any news about this ?

**Comment by joedragons** [comment]
@Turgon37 I don't have any info, I can tell you that Sonatype mostly monitors issues.sonatype.com for issues not github.  I've been advocating we just disable the issues and say that in various projects but not full luck so far.  You might try filing there too.

**Comment by Turgon37** [comment]
Bower is deprecated now, I close this because I don't use bower anymore
