### ISSUE TITLE
tough-cookie@2.2.2 deprecated

### ISSUE THREAD

**Issue by thimmy687** [sonatype/bower-nexus3-resolver#9]
tough-cookie@2.2.2 is deprecated and since npm tried to update this package I get the message:

bower <package name> MODULE_NOT_FOUND Cannot find module 'bower-nexus3-rosolver'

**Comment by joedragons** [comment]
@thimmy687 When are you getting that message?  When npm updates the bower-nexus3-resolver?

**Comment by thimmy687** [comment]
I got the message after a npm install request, but now after a reinstall it is working again from cmd.

Only in the Visual Studio is still this message, but I believe it is a Visual Studio problem.

**Comment by DarthHater** [comment]
@thimmy687 you figure out any more about this? I think we can close unless you have a reproducible path for us?
